name: LakeComo-Blevio
favicon: null
layout_spectrum: 0.8316687543410808
typography_spectrum: 0.04009510204195976
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
